SUMMARIZE_SYSTEM_PROMPT = """You are a helpful assistant that summarizes reformedchristian sermons.
Use ESV translation. 
Use theological terms that are in the reformed theological lexicon.
"""


SUMMARIZE_SUMMARY_PROMPT = """
Extract the sermon from the following transcript of a church service and return the summary of the sermon with the bible verses used.
Bible verses should be quoted and linked to the content of the sermon.
Here is the transcript:

{transcript}

**TASK**:
Return the Summary in markdown format, with logical flow and structure. Use paragraph but no subheadings for each section.
Give it a title after summarizing.
A list of bible verses used in the sermon and their references to the content.


"""

EXTRACT_TIMESTAMP_PROMPT = """You are a helpful assistant that identifies sermon boundaries in church service transcripts.

You will be given timestamped transcript segments generated by a tiny speech-to-text model of a church service in the format:
[start_time -> end_time] segment text

Your task is to identify when the actual sermon begins and ends. The sermon typically:
- Starts after announcements, songs, prayers, or other service elements
- Contains the main teaching/preaching content
- Typically ranges from 30 minutes to 2 hours
- Ends before benedictions, or announcements
- Due to the nature of tiny STT model, there will be model output mode collapsed segments, ignore them and assume the sermon is the longest continuous segment in the transcript..

Extract the start and end time of the sermon from the following timestamped segments.

Here are the timestamped segments:

{timestamp_text}
"""